version: '3.8'

services:
  db:
    image: postgres:15.6-bookworm
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tg-bot
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 100
      start_period: 5s
    ports:
      - "5432:5432"

  migrattions:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: no
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/tg-bot?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    entrypoint: sh -c "npm run migrate-up-ci"
